server:
  port: 8080


spring:
  application:
    name: FeiGong
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/FeiGong?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
      username: root
      password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml